# Generated by Django 3.1.4 on 2021-01-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=600)),
                ('Job_Title', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('EXT', models.IntegerField(max_length=15)),
                ('Dir_Phone', models.IntegerField(max_length=15)),
                ('Mobile', models.CharField(max_length=25)),
                ('Branch', models.CharField(max_length=300)),
            ],
        ),
    ]
