# Generated by Django 3.1.4 on 2021-01-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Dir_Phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='EXT',
            field=models.CharField(max_length=15),
        ),
    ]
