# Generated by Django 3.1.4 on 2021-01-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210117_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Branch',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Dir_Phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='EXT',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Full_Name',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Job_Title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Mobile',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
